### ISSUE TITLE
Problems in MD files

### ISSUE THREAD

**Issue by rebekaburnett** [vippsas/vipps-order-management-api#48]
I was testing this in Docusaurus (the new website tools we are working on) and I found a couple problems. There are several places where  <img...> is used, and these images are then broken. 

Can you change them to a format like this?  ` ![Vipps landing page](images/landing-page.png)`
 
Also, where there is not a blank line before a table, it doesn't render. 

Could you go fix these places (in both README.md and vipps-order-management-api.md)? 
 
 Thank you!!

**Comment by rebeksburnett** [comment]
These are in both README.md and vipps-order-management-api.md

**Comment by rebekaburnett** [comment]
Fixed in https://github.com/vippsas/vipps-order-management-api/pull/51
